export const ERROR_CODES = {
  // Authentication
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_ACCOUNT_CREATED: "AUTH_ACCOUNT_CREATED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_INVALID_REFRESH_TOKEN: "AUTH_INVALID_REFRESH_TOKEN",
  AUTH_ACCOUNT_INACTIVE: "AUTH_ACCOUNT_INACTIVE",
  AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  AUTH_CURRENT_USER_RETRIEVED: "AUTH_CURRENT_USER_RETRIEVED",
  AUTH_REGISTRATION_OPTIONS_RETRIEVED: "AUTH_REGISTRATION_OPTIONS_RETRIEVED",

  // Users
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_EMAIL_ALREADY_EXISTS: "USER_EMAIL_ALREADY_EXISTS",
  USER_PHONE_ALREADY_EXISTS: "USER_PHONE_ALREADY_EXISTS",
  USER_PROFILE_RETRIEVED: "USER_PROFILE_RETRIEVED",
  USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
  USER_PASSWORD_UPDATED: "USER_PASSWORD_UPDATED",
  USER_CURRENT_PASSWORD_INVALID: "USER_CURRENT_PASSWORD_INVALID",
  ROOMMATES_RETRIEVED: "ROOMMATES_RETRIEVED",

  // Properties
  PROPERTY_NOT_FOUND: "PROPERTY_NOT_FOUND",
  PROPERTY_ACCESS_DENIED: "PROPERTY_ACCESS_DENIED",
  PROPERTY_CREATED: "PROPERTY_CREATED",
  PROPERTY_UPDATED: "PROPERTY_UPDATED",
  PROPERTY_DEACTIVATED: "PROPERTY_DEACTIVATED",
  PROPERTY_DELETED: "PROPERTY_DELETED",
  PROPERTIES_RETRIEVED: "PROPERTIES_RETRIEVED",
  PROPERTY_RETRIEVED: "PROPERTY_RETRIEVED",
  PROPERTY_IMAGE_UPLOADED: "PROPERTY_IMAGE_UPLOADED",
  PROPERTY_IMAGE_DELETED: "PROPERTY_IMAGE_DELETED",
  PROPERTY_IMAGES_REORDERED: "PROPERTY_IMAGES_REORDERED",
  PROPERTY_IMAGE_NOT_FOUND: "PROPERTY_IMAGE_NOT_FOUND",
  PROPERTY_VIEW_RECORDED: "PROPERTY_VIEW_RECORDED",

  // Rooms
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_ACCESS_DENIED: "ROOM_ACCESS_DENIED",
  ROOM_FULL: "ROOM_FULL",
  ROOM_INVALID_CAPACITY: "ROOM_INVALID_CAPACITY",
  ROOM_CREATED: "ROOM_CREATED",
  ROOM_UPDATED: "ROOM_UPDATED",
  ROOM_DEACTIVATED: "ROOM_DEACTIVATED",
  ROOM_RETRIEVED: "ROOM_RETRIEVED",
  ROOMS_RETRIEVED: "ROOMS_RETRIEVED",
  ROOM_IMAGE_UPLOADED: "ROOM_IMAGE_UPLOADED",
  ROOM_IMAGE_DELETED: "ROOM_IMAGE_DELETED",
  ROOM_IMAGE_NOT_FOUND: "ROOM_IMAGE_NOT_FOUND",

  // Bookings
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  BOOKING_ACCESS_DENIED: "BOOKING_ACCESS_DENIED",
  BOOKING_ALREADY_EXISTS: "BOOKING_ALREADY_EXISTS",
  BOOKING_INVALID_STATUS: "BOOKING_INVALID_STATUS",
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_APPROVED: "BOOKING_APPROVED",
  BOOKING_REJECTED: "BOOKING_REJECTED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKINGS_RETRIEVED: "BOOKINGS_RETRIEVED",
  BOOKING_CANNOT_REQUEST_OWN_PROPERTY: "BOOKING_CANNOT_REQUEST_OWN_PROPERTY",
  BOOKING_ROOM_NOT_IN_PROPERTY: "BOOKING_ROOM_NOT_IN_PROPERTY",

  // Favorites
  FAVORITE_ADDED: "FAVORITE_ADDED",
  FAVORITE_REMOVED: "FAVORITE_REMOVED",
  FAVORITES_RETRIEVED: "FAVORITES_RETRIEVED",

  // Notifications
  NOTIFICATIONS_RETRIEVED: "NOTIFICATIONS_RETRIEVED",
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  NOTIFICATION_MARKED_READ: "NOTIFICATION_MARKED_READ",
  NOTIFICATIONS_ALL_MARKED_READ: "NOTIFICATIONS_ALL_MARKED_READ",
  NOTIFICATIONS_UNREAD_COUNT_RETRIEVED: "NOTIFICATIONS_UNREAD_COUNT_RETRIEVED",

  // Amenities
  AMENITIES_RETRIEVED: "AMENITIES_RETRIEVED",
  AMENITY_NOT_FOUND: "AMENITY_NOT_FOUND",

  // Locations
  LOCATIONS_RETRIEVED: "LOCATIONS_RETRIEVED",

  // Conversations & Messages
  CONVERSATION_CREATED: "CONVERSATION_CREATED",
  CONVERSATIONS_RETRIEVED: "CONVERSATIONS_RETRIEVED",
  CONVERSATION_RETRIEVED: "CONVERSATION_RETRIEVED",
  CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
  CONVERSATION_ACCESS_DENIED: "CONVERSATION_ACCESS_DENIED",
  CANNOT_CHAT_WITH_SELF: "CANNOT_CHAT_WITH_SELF",
  GENDER_MISMATCH_NOT_ALLOWED: "GENDER_MISMATCH_NOT_ALLOWED",
  INVALID_CHAT_PARTICIPANTS: "INVALID_CHAT_PARTICIPANTS",
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_DELETED: "MESSAGE_DELETED",
  MESSAGE_NOT_FOUND: "MESSAGE_NOT_FOUND",
  MESSAGE_DELETE_FORBIDDEN: "MESSAGE_DELETE_FORBIDDEN",
  MESSAGES_RETRIEVED: "MESSAGES_RETRIEVED",
  MESSAGES_MARKED_READ: "MESSAGES_MARKED_READ",
  UNREAD_MESSAGES_COUNT_RETRIEVED: "UNREAD_MESSAGES_COUNT_RETRIEVED",

  // Owner
  OWNER_DASHBOARD_RETRIEVED: "OWNER_DASHBOARD_RETRIEVED",
  OWNER_PROPERTIES_RETRIEVED: "OWNER_PROPERTIES_RETRIEVED",
  OWNER_BOOKINGS_RETRIEVED: "OWNER_BOOKINGS_RETRIEVED",

  // General
  HEALTH_CHECK_SUCCESS: "HEALTH_CHECK_SUCCESS",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  UPLOAD_FAILED: "UPLOAD_FAILED"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
